---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: grumpy
webhooks:
  - name: grumpy.giantswarm.io
    clientConfig:
      service:
        name: grumpy
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGekNDQXY4Q0ZDSGpxNXl4TnRrWnpKQ1pyblpMYjEvV0FOQy9NQTBHQ1NxR1NJYjNEUUVCRFFVQU1JSEgKTVFzd0NRWURWUVFHRXdKRVJURVFNQTRHQTFVRUNBd0hRMjlzYjJkdVpURVFNQTRHQTFVRUJ3d0hRMjlzYjJkdQpaVEVQTUEwR0ExVUVFUXdHTkRJME1qUXlNUlF3RWdZRFZRUUpEQXRJWVd4c2J5QWdNVFl5TVRFVE1CRUdBMVVFCkNnd0taMmxoYm5SemQyRnliVEVaTUJjR0ExVUVDd3dRUlcxdmFua2dSR1Z3WVhKMGJXVnVkREVXTUJRR0ExVUUKQXd3TloybGhiblJ6ZDJGeWJTNXBiekVsTUNNR0NTcUdTSWIzRFFFSkFSWVdibTh0Y21Wd2JIbEFaMmxoYm5SegpkMkZ5YlM1cGJ6QWVGdzB5TURFd01UTXhNREk0TlRKYUZ3MHlNREV4TVRJeE1ESTROVEphTUlISE1Rc3dDUVlEClZRUUdFd0pFUlRFUU1BNEdBMVVFQ0F3SFEyOXNiMmR1WlRFUU1BNEdBMVVFQnd3SFEyOXNiMmR1WlRFUE1BMEcKQTFVRUVRd0dOREkwTWpReU1SUXdFZ1lEVlFRSkRBdElZV3hzYnlBZ01UWXlNVEVUTUJFR0ExVUVDZ3dLWjJsaApiblJ6ZDJGeWJURVpNQmNHQTFVRUN3d1FSVzF2YW5rZ1JHVndZWEowYldWdWRERVdNQlFHQTFVRUF3d05aMmxoCmJuUnpkMkZ5YlM1cGJ6RWxNQ01HQ1NxR1NJYjNEUUVKQVJZV2JtOHRjbVZ3YkhsQVoybGhiblJ6ZDJGeWJTNXAKYnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFFMdzNxRW40WTljRUNxbDBNRAppekR0TzZRWEQ2SUtsczVJam93aEpIODFDVkVNZEN5aERYU09hSFRpVHI1ZGtCQ3BmVlUxSy9WNS8rNmFxdTRNCmt3eVZaU3M3Zy9sVTJwRHI0KzFBREtGbXhzeUMwVXExTnBNVU8zNWQrclJJWmxRZngwWjdMVEI1QXFYSjQrT0QKenI1cFFxQkRmczFBL3J2bXlZQUVlWkRGVUVqN1U1dFU1TktDTVp6QitDRTd4TWRSbklhelhlbStSVmp5WnV4VQo3d2pDM3BTSXJkWk1MOWdTK1hkVEdJRityNWpEc1Evc3J0c2ZOWWJwaDdWbk1oMGtLR0RWS0FGWGZVUUhtRUUwClVMYThQU2dpQWZNU1hRYzh5TW5RYmJ3Y2pKcW9TSUZhc2R3QTAxOTJyUHVGbU12VCtrTHQ2TVVTQVk1WDBZcEsKYy9FQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVEwRkFBT0NBUUVBTWt2RENGb3RySVRUSXNFbk9kWG0zUHpDOU9MTQpXdkU0VWhrdXk4WnhrcjRvZWNyT2Z3azNsVGFha2ZUY3psTEFKb2dnbWhVUU1GNVBLc0VhSzNJekVBbm1mZnVuCjdvWFJOZFV1ZjJHNVlvNDZFcDRzTmxwUXVtZGcydUhTcEJBWGNQR3lGSFh5MnRCRDgybFFPa2duNFB3c1hTaXQKUmFuRjhGZXVKOTJWL0x2RU9xcjJaTUZJRzBxUFFQNGY0VXpRMTRoRkxJS05FOGY1R1ZTWHB4ZlVGb1RrZCtZUQp2cjFmSWpkV05UbzNDcmt5WkpHUDMyWm4waEtZV1VMUlQ2MmdVNHRVT21qU0RHWk8vT0puUzJPVWVSVlpzQXo1CkxyV0pwTFE3SWR5c3pWMDRtbWFzd0NSTW0wS1lScE1ydHBYNGJ1VkRhWnczT2tEVEZsMUYrVCt2aFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
